config/routes.rb
Rails.application.routes.draw do
  apipie
  resources :shipment_methods
  resources :payment_methods
  root 'products#index'

  resources :positions
  devise_for :employees
  devise_for :clients
  resources :shipments
  resources :payments
  resources :statuses
  resources :orders
  resources :units
  resources :products
  resources :vendors
  resources :categories
  resources :thoughts
  resources :rates
  resources :images
  

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :orders
	has_many :thoughts
	has_many :rates
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_many :orders
	belongs_to :position
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/image.rb
# https://github.com/thoughtbot/paperclip/tree/master
class Image < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
 	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

 	belongs_to :product
end

app/models/order.rb
# Informację o przesyłce i zapłacie przenosimy do odpowiednich obiektów
# Relacja wygląda tak, ponieważ w jednej paczce może znajdować się wiele zamówień i za wiele zamówień można zapłacić w jednej płatności
class Order < ActiveRecord::Base
	belongs_to :payment
	belongs_to :shipment
	belongs_to :status
	has_many :units
	belongs_to :client
	belongs_to :employee
	def cost
		333
	end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
	has_many :orders
	belongs_to :payment_method
end

app/models/payment_method.rb
class PaymentMethod < ActiveRecord::Base
	has_many :payments
end

app/models/position.rb
class Position < ActiveRecord::Base
	has_many :employees
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	belongs_to :vendor
	has_many :units
	has_many :thoughts
	has_many :rates
	has_many :images

	def price
		netto_price + netto_price * vat
	end

	def amount
		units.count
	end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
	belongs_to :product
	belongs_to :client
end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
	has_many :orders
	belongs_to :shipment_method
end

app/models/shipment_method.rb
class ShipmentMethod < ActiveRecord::Base
	has_many :shipments
end

app/models/status.rb
class Status < ActiveRecord::Base
	has_many :orders
end

app/models/thought.rb
class Thought < ActiveRecord::Base
	belongs_to :product
	belongs_to :client
end

app/models/unit.rb
# Czas zakupu oraz ceny wypełniamy w momencie sprzedaży
# Dodajmy funkcję is_sold, sprawdzającą, czy czas zakupu nie jest nullem
class Unit < ActiveRecord::Base
	belongs_to :order
	belongs_to :product
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
	has_many :products
end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  before_action :set_payment_method, only: [:show, :edit, :update, :destroy]

  # GET /payment_methods
  # GET /payment_methods.json
  def index
    @payment_methods = PaymentMethod.all
  end

  # GET /payment_methods/1
  # GET /payment_methods/1.json
  def show
  end

  # GET /payment_methods/new
  def new
    @payment_method = PaymentMethod.new
  end

  # GET /payment_methods/1/edit
  def edit
  end

  # POST /payment_methods
  # POST /payment_methods.json
  def create
    @payment_method = PaymentMethod.new(payment_method_params)

    respond_to do |format|
      if @payment_method.save
        format.html { redirect_to @payment_method, notice: 'Payment method was successfully created.' }
        format.json { render :show, status: :created, location: @payment_method }
      else
        format.html { render :new }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_methods/1
  # PATCH/PUT /payment_methods/1.json
  def update
    respond_to do |format|
      if @payment_method.update(payment_method_params)
        format.html { redirect_to @payment_method, notice: 'Payment method was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_method }
      else
        format.html { render :edit }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_methods/1
  # DELETE /payment_methods/1.json
  def destroy
    @payment_method.destroy
    respond_to do |format|
      format.html { redirect_to payment_methods_url, notice: 'Payment method was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_method
      @payment_method = PaymentMethod.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_method_params
      params.require(:payment_method).permit(:name)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payment_methods_helper.rb
module PaymentMethodsHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/payment_methods/_form.html.erb
<%= form_for(@payment_method) do |f| %>
  <% if @payment_method.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment_method.errors.count, "error") %> prohibited this payment_method from being saved:</h2>

      <ul>
      <% @payment_method.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payment_methods/edit.html.erb
<h1>Editing Payment Method</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_method %> |
<%= link_to 'Back', payment_methods_path %>

app/views/payment_methods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Payment Methods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_methods.each do |payment_method| %>
      <tr>
        <td><%= payment_method.name %></td>
        <td><%= link_to 'Show', payment_method %></td>
        <td><%= link_to 'Edit', edit_payment_method_path(payment_method) %></td>
        <td><%= link_to 'Destroy', payment_method, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment method', new_payment_method_path %>

app/views/payment_methods/new.html.erb
<h1>New Payment Method</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_methods_path %>

app/views/payment_methods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @payment_method.name %>
</p>

<%= link_to 'Edit', edit_payment_method_path(@payment_method) %> |
<%= link_to 'Back', payment_methods_path %>