config/routes.rb
Rails.application.routes.draw do
  apipie
  resources :shipment_methods
  resources :payment_methods
  root 'products#index'

  resources :positions
  devise_for :employees
  devise_for :clients
  resources :shipments
  resources :payments
  resources :statuses
  resources :orders
  resources :units
  resources :products
  resources :vendors
  resources :categories
  resources :thoughts
  resources :rates
  resources :images
  

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :orders
	has_many :thoughts
	has_many :rates
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_many :orders
	belongs_to :position
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/image.rb
# https://github.com/thoughtbot/paperclip/tree/master
class Image < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
 	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

 	belongs_to :product
end

app/models/order.rb
# Informację o przesyłce i zapłacie przenosimy do odpowiednich obiektów
# Relacja wygląda tak, ponieważ w jednej paczce może znajdować się wiele zamówień i za wiele zamówień można zapłacić w jednej płatności
class Order < ActiveRecord::Base
	belongs_to :payment
	belongs_to :shipment
	belongs_to :status
	has_many :units
	belongs_to :client
	belongs_to :employee
	def cost
		333
	end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
	has_many :orders
	belongs_to :payment_method
end

app/models/payment_method.rb
class PaymentMethod < ActiveRecord::Base
	has_many :payments
end

app/models/position.rb
class Position < ActiveRecord::Base
	has_many :employees
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	belongs_to :vendor
	has_many :units
	has_many :thoughts
	has_many :rates
	has_many :images

	def price
		netto_price + netto_price * vat
	end

	def amount
		units.count
	end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
	belongs_to :product
	belongs_to :client
end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
	has_many :orders
	belongs_to :shipment_method
end

app/models/shipment_method.rb
class ShipmentMethod < ActiveRecord::Base
	has_many :shipments
end

app/models/status.rb
class Status < ActiveRecord::Base
	has_many :orders
end

app/models/thought.rb
class Thought < ActiveRecord::Base
	belongs_to :product
	belongs_to :client
end

app/models/unit.rb
# Czas zakupu oraz ceny wypełniamy w momencie sprzedaży
# Dodajmy funkcję is_sold, sprawdzającą, czy czas zakupu nie jest nullem
class Unit < ActiveRecord::Base
	belongs_to :order
	belongs_to :product
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
	has_many :products
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:product_id, :netto_price, :vat, :is_sold, :sold_at)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/units/_form.html.erb
<%= form_for(@unit) do |f| %>
  <% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% @unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :netto_price %><br>
    <%= f.text_field :netto_price %>
  </div>
  <div class="field">
    <%= f.label :vat %><br>
    <%= f.text_field :vat %>
  </div>
  <div class="field">
    <%= f.label :is_sold %><br>
    <%= f.check_box :is_sold %>
  </div>
  <div class="field">
    <%= f.label :sold_at %><br>
    <%= f.datetime_select :sold_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing Unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Units</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Netto price</th>
      <th>Vat</th>
      <th>Is sold</th>
      <th>Sold at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.product_id %></td>
        <td><%= unit.netto_price %></td>
        <td><%= unit.vat %></td>
        <td><%= unit.is_sold %></td>
        <td><%= unit.sold_at %></td>
        <td><%= link_to 'Show', unit %></td>
        <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
        <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unit', new_unit_path %>

app/views/units/new.html.erb
<h1>New Unit</h1>

<%= render 'form' %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @unit.product_id %>
</p>

<p>
  <strong>Netto price:</strong>
  <%= @unit.netto_price %>
</p>

<p>
  <strong>Vat:</strong>
  <%= @unit.vat %>
</p>

<p>
  <strong>Is sold:</strong>
  <%= @unit.is_sold %>
</p>

<p>
  <strong>Sold at:</strong>
  <%= @unit.sold_at %>
</p>

<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>