config/routes.rb
Rails.application.routes.draw do
  apipie
  resources :shipment_methods
  resources :payment_methods
  root 'products#index'

  resources :positions
  devise_for :employees
  devise_for :clients
  resources :shipments
  resources :payments
  resources :statuses
  resources :orders
  resources :units
  resources :products
  resources :vendors
  resources :categories
  resources :thoughts
  resources :rates
  resources :images
  

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :orders
	has_many :thoughts
	has_many :rates
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_many :orders
	belongs_to :position
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/image.rb
# https://github.com/thoughtbot/paperclip/tree/master
class Image < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
 	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

 	belongs_to :product
end

app/models/order.rb
# Informację o przesyłce i zapłacie przenosimy do odpowiednich obiektów
# Relacja wygląda tak, ponieważ w jednej paczce może znajdować się wiele zamówień i za wiele zamówień można zapłacić w jednej płatności
class Order < ActiveRecord::Base
	belongs_to :payment
	belongs_to :shipment
	belongs_to :status
	has_many :units
	belongs_to :client
	belongs_to :employee
	def cost
		333
	end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
	has_many :orders
	belongs_to :payment_method
end

app/models/payment_method.rb
class PaymentMethod < ActiveRecord::Base
	has_many :payments
end

app/models/position.rb
class Position < ActiveRecord::Base
	has_many :employees
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	belongs_to :vendor
	has_many :units
	has_many :thoughts
	has_many :rates
	has_many :images

	def price
		netto_price + netto_price * vat
	end

	def amount
		units.count
	end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
	belongs_to :product
	belongs_to :client
end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
	has_many :orders
	belongs_to :shipment_method
end

app/models/shipment_method.rb
class ShipmentMethod < ActiveRecord::Base
	has_many :shipments
end

app/models/status.rb
class Status < ActiveRecord::Base
	has_many :orders
end

app/models/thought.rb
class Thought < ActiveRecord::Base
	belongs_to :product
	belongs_to :client
end

app/models/unit.rb
# Czas zakupu oraz ceny wypełniamy w momencie sprzedaży
# Dodajmy funkcję is_sold, sprawdzającą, czy czas zakupu nie jest nullem
class Unit < ActiveRecord::Base
	belongs_to :order
	belongs_to :product
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
	has_many :products
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  before_action :set_thought, only: [:show, :edit, :update, :destroy]

  # GET /thoughts
  # GET /thoughts.json
  def index
    @thoughts = Thought.all
  end

  # GET /thoughts/1
  # GET /thoughts/1.json
  def show
  end

  # GET /thoughts/new
  def new
    @thought = Thought.new
  end

  # GET /thoughts/1/edit
  def edit
  end

  # POST /thoughts
  # POST /thoughts.json
  def create
    @thought = Thought.new(thought_params)

    respond_to do |format|
      if @thought.save
        format.html { redirect_to @thought, notice: 'Thought was successfully created.' }
        format.json { render :show, status: :created, location: @thought }
      else
        format.html { render :new }
        format.json { render json: @thought.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thoughts/1
  # PATCH/PUT /thoughts/1.json
  def update
    respond_to do |format|
      if @thought.update(thought_params)
        format.html { redirect_to @thought, notice: 'Thought was successfully updated.' }
        format.json { render :show, status: :ok, location: @thought }
      else
        format.html { render :edit }
        format.json { render json: @thought.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thoughts/1
  # DELETE /thoughts/1.json
  def destroy
    @thought.destroy
    respond_to do |format|
      format.html { redirect_to thoughts_url, notice: 'Thought was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thought
      @thought = Thought.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thought_params
      params.require(:thought).permit(:product_id, :client_id, :body)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/thoughts/_form.html.erb
<%= form_for(@thought) do |f| %>
  <% if @thought.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thought.errors.count, "error") %> prohibited this thought from being saved:</h2>

      <ul>
      <% @thought.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.number_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/thoughts/edit.html.erb
<h1>Editing Thought</h1>

<%= render 'form' %>

<%= link_to 'Show', @thought %> |
<%= link_to 'Back', thoughts_path %>

app/views/thoughts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Thoughts</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Client</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @thoughts.each do |thought| %>
      <tr>
        <td><%= thought.product_id %></td>
        <td><%= thought.client_id %></td>
        <td><%= thought.body %></td>
        <td><%= link_to 'Show', thought %></td>
        <td><%= link_to 'Edit', edit_thought_path(thought) %></td>
        <td><%= link_to 'Destroy', thought, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thought', new_thought_path %>

app/views/thoughts/new.html.erb
<h1>New Thought</h1>

<%= render 'form' %>

<%= link_to 'Back', thoughts_path %>

app/views/thoughts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @thought.product_id %>
</p>

<p>
  <strong>Client:</strong>
  <%= @thought.client_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @thought.body %>
</p>

<%= link_to 'Edit', edit_thought_path(@thought) %> |
<%= link_to 'Back', thoughts_path %>